### ISSUE TITLE
[Feature Request]: (HUGE LIST) Add compatibility for the following mods:

### ISSUE THREAD

**Issue by Numerosityy** [curryducker/ToolCompat#1]
### Feature Request

I don't expect you to add these all at once of course, but I've compiled a list of tools & materials I would like to see in this mod
(P.S. if you need help with textures I'd love to help you! DM me on Curseforge: Numerosityy)

Tools:
Shield (Shield Expansion)
Hammer (Stalwart Dungeons)
Chisel (Chisel and Bits)
Furnace (Quark) (Dunno if this counts, but would love to see furnace variants for various stone types)
Tools from any of the following weapon mods:
Additional Weapon and More
Simple Weapons for Better Combat (I like this the best personally)
Sniff's Weapons
Variant Tools and Weaponry

Materials:
Diopside, Aquite, Pyrope, Charoite, Horizonite (Blue Skies) (Possibly the wood & stone variant tools, but idrc about those tbh)
Pendorite (Oh The Biomes You'll Go)
Soul Steel (Spirit)
Golderite, Blazerite, Enderite, Prismarite, Phanterite, Featherite, Corrupterite, Echorite (Upgraded Netherite)
Ultimerite (Upgraded Netherite: Ultimerite)
Warden (Deeper and Darker)
Crystalline, Stellium (End's Phantasm)
Kiwano (Nether's Exoticism)
Tungsten, Chorundum (Stalwart Dungeons)
Rose Gold, Gilded Netherite (Additional Additions)
Necronium (Nourished Nether)
Adamantite (Enlightend)
Copper, Amethyst (Any equipment mod with these materials)
Electrum (Oreganized)

**Comment by curryducker** [comment]
Damn

**Comment by Numerosityy** [comment]
Lol yea, so what do you think? Can I help you out with textures?

**Comment by curryducker** [comment]
I will have to look at it later, can't work on this for at least a few days lol

**Comment by Numerosityy** [comment]
If you want, I can get started on textures for some of these, would love to save you some time

**Comment by Numerosityy** [comment]
So it's been a while, would you be interested in collabing on adding this compatibility? I can help make textures, you can add me on Discord 𝐍𝐮𝐦𝐞𝐫𝐨𝐬𝐢𝐭𝐲 ツ♡#3327

**Comment by curryducker** [comment]
could you join the discord server?

**Comment by Numerosityy** [comment]
Sure!
