### ISSUE TITLE
Incompatible with IDF ( Improved Damage Framework )

### ISSUE THREAD

**Issue by squarzyy** [curryducker/ToolCompat#2]
### Issue

1. What happened?
IDF have a problem when using Tool Compat, not sure which one is the main cause but here's the full log

2. What did you expect to happen?
Maybe IDF has changed the Tool Combat function

4. How can we reproduce the bug?
Using two Mod together ( Also Farmer's Delight and Nether's Delight )

### Latest version

- [X] I am running the latest version of the mod

### latest.log

https://bytebin.lucko.me/lOLwWLVi5Y
IDF have problem when using with Tool Compat, not sure which one is the main cause but here's the full log

**Comment by squarzyy** [comment]
Edit: Sorry, it was the other Mod causing it. Anyway, I love this Mod, hope there will be more updates. Thank you

**Comment by HUYBUSSIN** [comment]
Edit: yes it actually have a problem with IDF.
